In [1]:
list1 = range(1000000)
%time for i in range(1,10): [x*2 for x in list1]

Wall time: 1.8 s


In [2]:
import numpy as np
list2 = np.arange(1000000)
%time list2 * 2

Wall time: 2.99 ms


array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [3]:
z = np.zeros((4,4))
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
z = np.ones((4,4))
print(z)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
z = np.empty((4,4))
print(z)
# Data Can be anything other

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
list1 = [1,4,5,7]
np.array(list1)

array([1, 4, 5, 7])

In [7]:
np.arange(1,100000,100)

array([    1,   101,   201,   301,   401,   501,   601,   701,   801,
         901,  1001,  1101,  1201,  1301,  1401,  1501,  1601,  1701,
        1801,  1901,  2001,  2101,  2201,  2301,  2401,  2501,  2601,
        2701,  2801,  2901,  3001,  3101,  3201,  3301,  3401,  3501,
        3601,  3701,  3801,  3901,  4001,  4101,  4201,  4301,  4401,
        4501,  4601,  4701,  4801,  4901,  5001,  5101,  5201,  5301,
        5401,  5501,  5601,  5701,  5801,  5901,  6001,  6101,  6201,
        6301,  6401,  6501,  6601,  6701,  6801,  6901,  7001,  7101,
        7201,  7301,  7401,  7501,  7601,  7701,  7801,  7901,  8001,
        8101,  8201,  8301,  8401,  8501,  8601,  8701,  8801,  8901,
        9001,  9101,  9201,  9301,  9401,  9501,  9601,  9701,  9801,
        9901, 10001, 10101, 10201, 10301, 10401, 10501, 10601, 10701,
       10801, 10901, 11001, 11101, 11201, 11301, 11401, 11501, 11601,
       11701, 11801, 11901, 12001, 12101, 12201, 12301, 12401, 12501,
       12601, 12701,

In [9]:
z.shape

(4, 4)

In [12]:
z.reshape((2,2,2,2))

array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]])

In [13]:
z.ndim

2

In [14]:
a = np.random.randn((10))
b = np.random.randn((10))
print(a,b)

[-0.55660821 -0.43883506  0.05232754  2.67982762  0.58402    -1.17836091
 -0.59724488 -0.65120171 -1.97152944  0.02751215] [-1.11945844  1.74630194  0.30554274  0.0758087   0.68311278 -0.29056606
 -0.07910042  0.19021913 -0.5623208  -1.14076661]


In [15]:
a+b

array([-1.67606665,  1.30746688,  0.35787029,  2.75563632,  1.26713277,
       -1.46892698, -0.6763453 , -0.46098257, -2.53385024, -1.11325446])

In [16]:
a-b

array([ 0.56285023, -2.18513699, -0.2532152 ,  2.60401892, -0.09909278,
       -0.88779485, -0.51814445, -0.84142084, -1.40920864,  1.16827876])

In [17]:
a*b

array([ 0.62309976, -0.76633851,  0.0159883 ,  0.20315426,  0.39895152,
        0.34239169,  0.04724232, -0.12387103,  1.10863202, -0.03138494])

In [18]:
a/b

array([ 4.97212037e-01, -2.51293918e-01,  1.71260961e-01,  3.53498674e+01,
        8.54939352e-01,  4.05539762e+00,  7.55046388e+00, -3.42342903e+00,
        3.50605817e+00, -2.41172463e-02])

In [19]:
a**2

array([3.09812702e-01, 1.92576206e-01, 2.73817188e-03, 7.18147607e+00,
       3.41079356e-01, 1.38853444e+00, 3.56701442e-01, 4.24063665e-01,
       3.88692834e+00, 7.56918363e-04])

In [20]:
a>0

array([False, False,  True,  True,  True, False, False, False, False,
        True])

In [21]:
a[a>0]

array([0.05232754, 2.67982762, 0.58402   , 0.02751215])

In [22]:
x=np.array([1,7,9,8,5])
x[4]

5

In [23]:
x[x>5]

array([7, 9, 8])

In [24]:
x[[2,1]]

array([9, 7])

In [26]:
x=np.random.randn(10,10)

In [27]:
x[0]

array([-0.59913338, -1.31359109,  0.06117007,  0.04918672,  2.27665116,
       -0.67599949, -0.55017781, -0.05907074, -0.08149436,  0.75401675])

In [28]:
x[1::2]
#Odd Rows

array([[ 0.49283964,  0.58324445,  0.94512305, -1.09250583,  0.96236237,
         0.34735196,  0.01140663, -0.23400425, -1.6050693 , -0.76720054],
       [-1.85748194, -0.38193457,  0.74662982,  0.27462848, -1.53778337,
        -0.33470682, -0.61127783, -1.40470318, -0.93904143,  0.00328123],
       [ 0.03353771, -0.79387656, -0.21287816, -0.40393393, -1.37319858,
        -2.11995377, -2.12387941,  0.7561239 , -0.60010335,  0.48947629],
       [-0.65333019, -0.39793438, -0.37212895,  0.2696708 , -1.46938988,
        -1.98650134, -0.06769997,  0.57102991,  0.25650118,  0.42151129],
       [-1.36162514,  2.51323426, -0.0256358 , -1.22860864,  0.1257458 ,
        -1.41887242,  0.37121341,  2.12522541,  0.19652052, -0.73329976]])

In [29]:
x[::,0:4]

array([[-0.59913338, -1.31359109,  0.06117007,  0.04918672],
       [ 0.49283964,  0.58324445,  0.94512305, -1.09250583],
       [ 0.30276866,  2.03734635,  0.58468019,  0.8902958 ],
       [-1.85748194, -0.38193457,  0.74662982,  0.27462848],
       [ 0.01611896, -0.49083218, -0.72658463,  0.11910247],
       [ 0.03353771, -0.79387656, -0.21287816, -0.40393393],
       [-1.11863818,  0.30141448,  0.35131367,  0.38959864],
       [-0.65333019, -0.39793438, -0.37212895,  0.2696708 ],
       [ 0.60961244, -2.02585258,  0.84218257, -0.66441958],
       [-1.36162514,  2.51323426, -0.0256358 , -1.22860864]])

In [30]:
#Making a square with ones in border and zeroes in center
square = np.ones((5,5))
square[1:-1,1:-1]=0

In [31]:
square

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
x=np.array([10,9,8,6,11])
np.sqrt(x)

array([3.16227766, 3.        , 2.82842712, 2.44948974, 3.31662479])

In [33]:
np.power(x,2)

array([100,  81,  64,  36, 121], dtype=int32)

In [34]:
y=np.array([7,11,3,8,10])
np.maximum(x,y)

array([10, 11,  8,  8, 11])

In [36]:
np.max(x)

11

In [37]:
x=np.array([0,-1,10000,111,22121])
np.where(x<=0,25000,x)

array([25000, 25000, 10000,   111, 22121])

In [38]:
np.where(x<=0,25000,"NOT OK")

array(['25000', '25000', 'NOT OK', 'NOT OK', 'NOT OK'], dtype='<U11')

In [39]:
print(True+True)

2


In [40]:
x=np.array([10,9,7,10,7])
x.mean()

8.6

In [42]:
x.cumsum()

array([10, 19, 26, 36, 43], dtype=int32)

In [46]:
y = x>8
print(y)

[ True  True False  True False]


In [44]:
y.sum()

3

In [45]:
y.any()

True

In [47]:
y.all()

False

In [49]:
x.sort()
x

array([ 7,  7,  9, 10, 10])

# File I/O

In [21]:
x=[1,4,5,7,1]
y=[8,7,9]
np.savez('testx',x=x,y=y)
loading = np.load('testx.npz')
loading
loading['y']

array([8, 7, 9])

# LA

In [25]:
x=np.random.randn(3,2)
y=np.random.randn(2,3)
x

array([[ 1.12174786,  0.79905237],
       [ 0.0414948 ,  0.31803897],
       [-0.20565384,  0.71344635]])

In [26]:
y

array([[-0.07861379, -1.06694856,  1.32366801],
       [ 1.55550578,  2.09772559,  0.14447667]])

In [27]:
x.dot(y)

array([[ 1.15474573,  0.47934533,  1.60026618],
       [ 0.4914494 ,  0.62288567,  0.10087456],
       [ 1.12593715,  1.71603674, -0.16914105]])

In [28]:
x.transpose()

array([[ 1.12174786,  0.0414948 , -0.20565384],
       [ 0.79905237,  0.31803897,  0.71344635]])

# Pseudo Random Numbers

In [30]:
np.random.seed(7)
np.random.normal(size=(3,3))

array([[ 1.69052570e+00, -4.65937371e-01,  3.28201637e-02],
       [ 4.07516283e-01, -7.88923029e-01,  2.06557291e-03],
       [-8.90385858e-04, -1.75472431e+00,  1.01765801e+00]])

In [32]:
x=np.random.randn(4,5)
x.reshape(2,2,5)

array([[[ 0.60049852, -0.62542897, -0.17154826,  0.50529937,
         -0.26135642],
        [-0.24274908, -1.45324141,  0.55458031,  0.12388091,
          0.27445992]],

       [[-1.52652453,  1.65069969,  0.15433554, -0.38713994,
          2.02907222],
        [-0.04538603, -1.4506787 , -0.40522786, -2.2883151 ,
          1.04939655]]])

In [33]:
x.ravel()

array([ 0.60049852, -0.62542897, -0.17154826,  0.50529937, -0.26135642,
       -0.24274908, -1.45324141,  0.55458031,  0.12388091,  0.27445992,
       -1.52652453,  1.65069969,  0.15433554, -0.38713994,  2.02907222,
       -0.04538603, -1.4506787 , -0.40522786, -2.2883151 ,  1.04939655])

In [34]:
x.flatten()

array([ 0.60049852, -0.62542897, -0.17154826,  0.50529937, -0.26135642,
       -0.24274908, -1.45324141,  0.55458031,  0.12388091,  0.27445992,
       -1.52652453,  1.65069969,  0.15433554, -0.38713994,  2.02907222,
       -0.04538603, -1.4506787 , -0.40522786, -2.2883151 ,  1.04939655])

In [35]:
x = np.arange(100)

In [36]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [43]:
x.reshape(50,2,order='F')

array([[ 0, 50],
       [ 1, 51],
       [ 2, 52],
       [ 3, 53],
       [ 4, 54],
       [ 5, 55],
       [ 6, 56],
       [ 7, 57],
       [ 8, 58],
       [ 9, 59],
       [10, 60],
       [11, 61],
       [12, 62],
       [13, 63],
       [14, 64],
       [15, 65],
       [16, 66],
       [17, 67],
       [18, 68],
       [19, 69],
       [20, 70],
       [21, 71],
       [22, 72],
       [23, 73],
       [24, 74],
       [25, 75],
       [26, 76],
       [27, 77],
       [28, 78],
       [29, 79],
       [30, 80],
       [31, 81],
       [32, 82],
       [33, 83],
       [34, 84],
       [35, 85],
       [36, 86],
       [37, 87],
       [38, 88],
       [39, 89],
       [40, 90],
       [41, 91],
       [42, 92],
       [43, 93],
       [44, 94],
       [45, 95],
       [46, 96],
       [47, 97],
       [48, 98],
       [49, 99]])

In [44]:
x.reshape(50,2,order='C')

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39],
       [40, 41],
       [42, 43],
       [44, 45],
       [46, 47],
       [48, 49],
       [50, 51],
       [52, 53],
       [54, 55],
       [56, 57],
       [58, 59],
       [60, 61],
       [62, 63],
       [64, 65],
       [66, 67],
       [68, 69],
       [70, 71],
       [72, 73],
       [74, 75],
       [76, 77],
       [78, 79],
       [80, 81],
       [82, 83],
       [84, 85],
       [86, 87],
       [88, 89],
       [90, 91],
       [92, 93],
       [94, 95],
       [96, 97],
       [98, 99]])

# Concatenate

In [54]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[3,2,1],[7,6,5]])
np.concatenate((arr1,arr2),axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [3, 2, 1],
       [7, 6, 5]])

In [56]:
d = np.array([1,4,5,6,7,9,1,4])
np.split(d,[2,5])

[array([1, 4]), array([5, 6, 7]), array([9, 1, 4])]

In [58]:
d = np.array([[1,4,5,6],[7,9,1,4]])
np.split(d,[2,5],axis=1)

[array([[1, 4],
        [7, 9]]), array([[5, 6],
        [1, 4]]), array([], shape=(2, 0), dtype=int32)]

In [59]:
d=np.array([1,5,7,8])

In [62]:
np.repeat(d,2)

array([1, 1, 5, 5, 7, 7, 8, 8])

In [65]:
np.tile(d,2)

array([1, 5, 7, 8, 1, 5, 7, 8])