In [3]:
import numpy as np
a = np.arange(1,28).reshape((3,3,3))
print(a)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [4]:
print(a.shape)

(3, 3, 3)


In [5]:
print(a.ndim)

3


In [6]:
a += a
print(a)

[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[20 22 24]
  [26 28 30]
  [32 34 36]]

 [[38 40 42]
  [44 46 48]
  [50 52 54]]]


In [19]:
a = np.random.rand(3,4,5)
print(a)

[[[0.54776955 0.58224724 0.40946126 0.39921912 0.83835373]
  [0.75383069 0.92443643 0.03126985 0.2739303  0.54094574]
  [0.60506028 0.71971083 0.0683005  0.11494305 0.68407298]
  [0.67734388 0.46612772 0.36691568 0.83032089 0.43630731]]

 [[0.24404705 0.02705113 0.48295927 0.80626108 0.36461619]
  [0.04663942 0.20493265 0.14452021 0.30395694 0.35544547]
  [0.19673202 0.63811531 0.54318108 0.65730707 0.80971185]
  [0.91611331 0.15896419 0.55154876 0.82508614 0.73028266]]

 [[0.00314909 0.7916799  0.19795338 0.54451232 0.95251199]
  [0.01194813 0.22404923 0.54221407 0.0472597  0.09201298]
  [0.99596696 0.42784045 0.77813611 0.06352754 0.49634553]
  [0.82580356 0.49670854 0.88141605 0.50957142 0.27061821]]]


In [20]:
arr = [1,2,3]
print(type(a))

<class 'numpy.ndarray'>


In [21]:
a = np.array(a)
type(a)

numpy.ndarray

# np.array

In [22]:
List = [1,2,3]
a = np.array(List)
a is List

False

In [23]:
a is not List

True

In [24]:
b = np.array(a)
a is b

False

In [27]:
a = np.asarray(List)
b = np.asarray(a)
a is b

True

In [28]:
%history

import numpy as np
a = np.arange(1,28).reshape((3,3,3))
import numpy as np
a = np.arange(1,28).reshape((3,3,3))
print(a)
import numpy as np
a = np.arange(1,28).reshape((3,3,3))
print(a)
print(a.shape)
print(a.ndim)
a += a
print(a)
a = np.random.randn(2,6)
a = np.random.randn(2,6)
print(a)
a = np.random.randn(3,6)
print(a)
a = np.random.randn(3,6,4)
print(a)
a = np.random.rand(3,6,4)
print(a)
a = np.random.randint(3,6,4)
print(a)
a = np.random.rand(3,6,4)
print(a)
a = np.random.randint(3,6,4)
print(a)
a = np.random.random_integers(3,6,4)
print(a)
a = np.random.rand(3,6,4)
print(a)
a = np.random.rand(3)
print(a)
a = np.random.rand(3,4)
print(a)
a = np.random.rand(3,4,5)
print(a)
arr = [1,2,3]
print(type(a))
a = np.array(a)
type(a)
List = [1,2,3]
a = np.array(List)
a is List
a is not List
b = np.array(a)
a is b
a = np.asarray(List)
b = np.asarray(List)
a = np.asarray(List)
b = np.asarray(List)
a is b
a = np.asarray(List)
b = np.asarray(a)
a is b
%history


In [30]:
%time list(range(10000000))[:20]

Wall time: 823 ms


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [31]:
%time np.arange(10000000)[:20]

Wall time: 43.9 ms


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [32]:
print("Waleed\nButt")

Waleed
Butt


In [34]:
print("Waleed\\nButt")

Waleed\nButt
