In [2]:
import numpy as np
matrix = np.random.randn(3,2)
matrix

array([[-1.35612917,  0.26380786],
       [ 0.38154776,  1.00188238],
       [ 0.63608148, -0.10286974]])

In [3]:
np.transpose(matrix)

array([[-1.35612917,  0.38154776,  0.63608148],
       [ 0.26380786,  1.00188238, -0.10286974]])

In [14]:
%time np.arange(1,7).reshape((3,2))

Wall time: 0 ns


array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
np.transpose(matrix)

array([[1, 3, 5],
       [2, 4, 6]])

In [15]:
np.arange(1,7).reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
matrix = np.arange(1,37).reshape((3,4,3))
matrix.transpose((0,1,2))
matrix

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [48]:
np.arange(1,13,dtype='float').reshape((3,4))

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])