In [1]:
import numpy as np
import pandas as pd
arr = np.arange(16).reshape((2,2,4))
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [2]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [3]:
arr.transpose((1,2,0))

array([[[ 0,  8],
        [ 1,  9],
        [ 2, 10],
        [ 3, 11]],

       [[ 4, 12],
        [ 5, 13],
        [ 6, 14],
        [ 7, 15]]])

In [4]:
arr = np.arange(32).reshape((4,4,2))
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [5]:
arr.transpose((1,2,0))

array([[[ 0,  8, 16, 24],
        [ 1,  9, 17, 25]],

       [[ 2, 10, 18, 26],
        [ 3, 11, 19, 27]],

       [[ 4, 12, 20, 28],
        [ 5, 13, 21, 29]],

       [[ 6, 14, 22, 30],
        [ 7, 15, 23, 31]]])

In [6]:
arr.swapaxes(1,2)

array([[[ 0,  2,  4,  6],
        [ 1,  3,  5,  7]],

       [[ 8, 10, 12, 14],
        [ 9, 11, 13, 15]],

       [[16, 18, 20, 22],
        [17, 19, 21, 23]],

       [[24, 26, 28, 30],
        [25, 27, 29, 31]]])

In [7]:
get_ipython().system('type examples/ex1.csv')

The syntax of the command is incorrect.


In [8]:
pd.read_csv('examples/ex1.csv')

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [9]:
pd.read_table('examples/ex1.csv', sep=',')

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [10]:
pd.read_csv('examples/ex2.csv', header=None)

0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [11]:
pd.read_csv('examples/ex2.csv', names=['a', 'b', 'c', 'd', 'message'])

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [12]:
pd.read_csv('examples/ex2.csv', names=['a', 'b', 'c', 'd', 'message'], index_col='message')

a   b   c   d
message               
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [13]:
pd.read_csv('examples/ex1.csv',index_col='b')

a   c   d message
b                    
2   1   3   4   hello
6   5   7   8   world
10  9  11  12     foo

In [14]:
pd.read_csv('examples/csv_mindex.csv',index_col=['key1', 'key2'])

value1  value2
key1 key2                
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [15]:
pd.read_csv('examples/csv_mindex.csv')

key1 key2  value1  value2
0  one    a       1       2
1  one    b       3       4
2  one    c       5       6
3  one    d       7       8
4  two    a       9      10
5  two    b      11      12
6  two    c      13      14
7  two    d      15      16

In [16]:
pd.read_csv('examples/csv_mindex.csv',index_col=['key1'])

key2  value1  value2
key1                     
one     a       1       2
one     b       3       4
one     c       5       6
one     d       7       8
two     a       9      10
two     b      11      12
two     c      13      14
two     d      15      16

In [17]:
pd.read_table('examples/ex3.txt', sep='\s+')

A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [18]:
pd.read_csv('examples/ex4.csv', skiprows=[0, 2, 3])

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [19]:
pd.read_csv('examples/ex5.csv')

something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [20]:
pd.isnull(pd.read_csv('examples/ex5.csv'))

something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

In [21]:
pd.read_csv('examples/ex5.csv', na_values=['NULL'])

something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [22]:
pd.read_csv('examples/ex5.csv', na_values={'message': ['foo', 'NA'], 'something': ['two']})

something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       NaN  5   6   NaN   8   world
2     three  9  10  11.0  12     NaN